version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: 'mongodb+srv://47mycloset:gMBn0Jj9XXvIS5ez@cluster0.00xlx.mongodb.net/kanban-app'
      NODE_ENV: 'production'
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      REACT_APP_API_URL: 'http://localhost:3000'
    restart: unless-stopped
