name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    name: Frontend Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install

      - name: Lint frontend code
        run: npx eslint --config eslint.config.cjs "src/**/*.{js,jsx,ts,tsx}"

      - name: Run frontend tests
        run: npm test -- --watchAll=false

  backend:
    name: Backend Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install

      - name: Run TypeScript type-check
        run: npx tsc --noEmit
